[target.riscv64gc-unknown-linux-musl]
linker = "/opt/riscv-musl/riscv64-lp64d--musl--stable-2024.05-1/bin/riscv64-buildroot-linux-musl-gcc.br_real"
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=--sysroot=/opt/riscv-musl/riscv64-lp64d--musl--stable-2024.05-1/riscv64-buildroot-linux-musl/sysroot",
    # "-C", "target-feature=+crt-static", # Uncomment me to force static compilation
    # "-C", "panic=abort", # Uncomment me to avoid compiling in panics
]
